version: '2.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio_bertil
    container_name: portfolio
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.porfolio.rule=Host(`bertil.re`)"
      - "traefik.http.routers.porfolio.entrypoints=web,websecure"
      # Indique à Traefik le port interne sur lequel le service écoute (ici 80)
      - "traefik.http.services.porfolio.loadbalancer.server.port=80"
      - "traefik.docker.network=webTraefik"  # Réseau Docker utilisé par Traefik
    volumes:
      - .:/var/www/
    networks:
      - webTraefik
volumes:
  db-data:

networks:
  webTraefik:
    external: true  # Utiliser le réseau externe créé par Traefik