name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
  VPS_HOST: ${{ secrets.VPS_HOST }}
  APP_PATH: ${{ secrets.VPS_DIRECTORY }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: vps_hostinger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass

      - name: Copy files to VPS
        run: sshpass -p $VPS_PASSWORD scp -o StrictHostKeyChecking=no -r ./* $VPS_USER@$VPS_HOST:$APP_PATH

      - name: Deploy the new image
        uses: appleboy/ssh-action@master
        env:
          PATH_DIRECTORY: ${{ secrets.VPS_DIRECTORY }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          envs:  PATH_DIRECTORY
          script: |
            cd $PATH_DIRECTORY
            ls -al
            cat << EOF > .env
              SMTP_HOST=${{ secrets.SMTP_HOST }}
              SMTP_USER=${{ secrets.SMTP_USER }}
              SMTP_PORT=${{ secrets.SMTP_PORT }}
              SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
              KEY_SECRET_RECAPTCHA=${{ secrets.KEY_SECRET_RECAPTCHA }}
            EOF
            chmod 644 .env
            docker compose down
            docker compose up -d --build